// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.62.1.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member

import "bridge_definitions.dart";
import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'bridge_generated.dart';
export 'bridge_generated.dart';

class RustlibPlatform extends FlutterRustBridgeBase<RustlibWire> with FlutterRustBridgeSetupMixin {
  RustlibPlatform(FutureOr<WasmModule> dylib) : super(RustlibWire(dylib)) {
    setupMixinConstructor();
  }
  Future<void> setup() => inner.init;

// Section: api2wire

  @protected
  Uint8List api2wire_uint_8_list(Uint8List raw) {
    return raw;
  }
// Section: finalizer
}

// Section: WASM wire module

@JS('wasm_bindgen')
external RustlibWasmModule get wasmModule;

@JS()
@anonymous
class RustlibWasmModule implements WasmModule {
  external Object /* Promise */ call([String? moduleName]);
  external RustlibWasmModule bind(dynamic thisArg, String moduleName);
  external dynamic /* void */ wire_rust_crop_image(NativePortType port_, Uint8List image_bytes);
}

// Section: WASM wire connector

class RustlibWire extends FlutterRustBridgeWasmWireBase<RustlibWasmModule> {
  RustlibWire(FutureOr<WasmModule> module) : super(WasmModule.cast<RustlibWasmModule>(module));

  void wire_rust_crop_image(NativePortType port_, Uint8List image_bytes) => wasmModule.wire_rust_crop_image(port_, image_bytes);
}
