name: yomu
description: An android comic reading app.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cached_network_image: ^3.2.2
  file_picker: ^5.2.0+1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.9
  get: ^4.6.5
  html: null
  http: null
  infinite_scroll_pagination: ^3.2.0
  isar: 3.0.0
  isar_flutter_libs: 3.0.0
  logger: ^1.1.0
  path_provider: ^2.0.11
  permission_handler: ^10.1.0
  streaming_shared_preferences: ^2.0.0
  url_launcher: ^6.1.5

dev_dependencies:
  build_runner: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: 3.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/splash-icon.png
  # fonts:
  #   - family: Nunito
  #     fonts:
  #      - asset: assets/Fonts/Nunito/Nunito.ttf
