name: himotoku
description: An android comic reading app.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# major.minor.patch+build
# patch -> fix small issues in previous build.
# minor -> minor improvements, minor api change etc
# major -> Big changes/breaking changes
# build -> beta: unstable code, rc, stable, nightly
# Order: stable > rc > nightly/dev > beta > alpha
version: 0.1.0-alpha

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  archive: ^3.3.5
  cached_network_image: ^3.2.2
  file_picker: ^5.2.0+1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_isolate: ^2.0.4
  flutter_local_notifications: ^13.0.0
  flutter_markdown: ^0.6.13
  flutter_native_splash: ^2.2.9
  flutter_rust_bridge: ^1.59.0
  freezed_annotation: ^2.2.0
  html: ^0.15.1
  http: ^0.13.5
  infinite_scroll_pagination: ^3.2.0
  isar: ^3.0.2
  isar_flutter_libs: ^3.0.2
  path_provider: ^2.0.11
  permission_handler: ^10.1.0
  url_launcher: ^6.1.5
  version: ^3.0.2
  yaml: ^3.1.1
  ffi: ^2.0.1

dev_dependencies:
  build_runner: null
  flutter_lints: ^2.0.0
  ffigen: ^7.2.0
  # flutter_test:
  #   sdk: flutter
  freezed: ^2.3.2
  isar_generator: ^3.0.2

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/splash-icon.png
    - pubspec.yaml
  # fonts:
  #   - family: Nunito
  #     fonts:
  #      - asset: assets/Fonts/Nunito/Nunito.ttf
