name: himotoku
description: An android comic reading app.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# major.minor.patch+build
# patch -> fix small issues in previous build.
# minor -> minor improvements, minor api change etc
# major -> Big changes/breaking changes
# build -> beta: unstable code, rc, stable, nightly
# Order: stable > rc > nightly/dev > beta > alpha
version: 0.1.1-alpha

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  archive: ^3.3.5
  cached_network_image: ^3.2.2
  ffi: ^2.0.1
  file_picker: ^5.2.0+1
  firebase_core: ^2.7.1
  firebase_crashlytics: ^3.0.16
  firebase_performance: ^0.9.0+15
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_downloader: ^1.10.2
  flutter_isolate: ^2.0.4
  flutter_local_notifications: ^14.0.0+1
  flutter_markdown: ^0.6.13
  flutter_native_splash: ^2.2.9
  flutter_rust_bridge: ^1.59.0
  freezed_annotation: ^2.2.0
  google_fonts: ^4.0.4
  html: ^0.15.1
  http: ^0.13.5
  infinite_scroll_pagination: ^3.2.0
  inview_notifier_list: ^3.0.0
  isar: ^3.0.2
  isar_flutter_libs: ^3.0.2
  jiffy: ^6.1.0
  json_annotation: ^4.8.0
  path_provider: ^2.0.11
  permission_handler: ^10.1.0
  rechron: ^0.2.0
  url_launcher: ^6.1.5
  version: ^3.0.2
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.3.3
  ffigen: ^7.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  # flutter_test:
  #   sdk: flutter
  freezed: ^2.3.2
  isar_generator: ^3.0.2

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/splash.png
    - assets/splash-light.png
    - pubspec.yaml
    - assets/fonts/Inter/

flutter_icons:
  android: true
  ios: false
  image_path: "assets/ic_launcher.png"

  min_sdk_android: 16 # android min sdk min:16, default 21
